var currentfilms = [
  {
    "company": "Adox",
    "name": "Adox CHS 100 II",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 992,
    "description": "orthopanchromatic film with a classic emulsion and a sensitization optimized for greyscale separation",
    "launched": 2015,
    "datasheet": "datasheets/adox-chs-100-ii.pdf",
    "lomography": "https://www.lomography.com/films/871958938-adox-chs-100-ii/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20CHS%20100%20II%22",
    "image": "adox-chs-100-ii-120.png"
  },
  {
    "company": "Adox",
    "name": "Adox CHS 100 II",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 992,
    "description": "orthopanchromatic film with a classic emulsion and a sensitization optimized for greyscale separation",
    "launched": 2013,
    "datasheet": "datasheets/adox-chs-100-ii.pdf",
    "lomography": "https://www.lomography.com/films/871958938-adox-chs-100-ii/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20CHS%20100%20II%22",
    "image": "adox-chs-100-ii-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox CMS 20 II",
    "iso": "20",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 1507,
    "description": "the sharpest, most fine grained and highest resolving film, orthopanchromatic",
    "launched": 2011,
    "datasheet": "datasheets/adox-cms-20-ii.pdf",
    "lomography": "https://www.lomography.com/films/871965093-adox-cms-20-ii/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20CMS%2020%20II%22",
    "image": "adox-cms-20-ii-120.png"
  },
  {
    "company": "Adox",
    "name": "Adox CMS 20 II",
    "iso": "20",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 1507,
    "description": "the sharpest, most fine grained and highest resolving film, orthopanchromatic",
    "launched": 2011,
    "datasheet": "datasheets/adox-cms-20-ii.pdf",
    "lomography": "https://www.lomography.com/films/871965093-adox-cms-20-ii/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20CMS%2020%20II%22",
    "image": "adox-cms-20-ii-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox Color Implosion",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 5065,
    "description": "film with a partially collapsed color coupling system for unpredictable results. effective speed is ISO 100",
    "launched": 2012,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871951418-adox-color-implosion/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20Color%20Implosion%22",
    "image": "adox-color-implosion-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox HR-50",
    "iso": "50",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 744,
    "description": "superpanchromatic film with a high contrast",
    "launched": 2018,
    "datasheet": "datasheets/adox-hr-50.pdf",
    "lomography": "https://www.lomography.com/films/871968181-adox-hr-50/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20HR-50%22",
    "image": "adox-hr-50-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox Scala 50",
    "iso": "50",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 4,
    "description": "superpanchromatic film with a clear base intended for reversal processing",
    "launched": 2019,
    "datasheet": "",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20Scala%2050%22",
    "image": "adox-scala-50-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox Scala 160",
    "iso": "160",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 425,
    "description": "panchromatic film with a clear base intended for reversal processing",
    "launched": 2016,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871965587-adox-scala-160/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20Scala%20160%22",
    "image": "adox-scala-160-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox Silvermax 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 5273,
    "description": "orthopanchromatic film with a classic emulsion, a clear base and an extreme exposure latitude",
    "launched": 2012,
    "datasheet": "datasheets/adox-silvermax-100.pdf",
    "lomography": "https://www.lomography.com/films/871953394-adox-silvermax-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20Silvermax%20100%22",
    "image": "adox-silvermax-100-135.png"
  },
  {
    "company": "Agfaphoto",
    "name": "Agfaphoto APX 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 56771,
    "description": "cheap panchromatic film with a classic emulsion that can be used universally and is suitable for a variety of applications",
    "launched": 2013,
    "datasheet": "datasheets/agfaphoto-apx-100.pdf",
    "lomography": "https://www.lomography.com/films/871912608-agfa-apx-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22APX%20100%22",
    "image": "agfaphoto-apx-100-135.png"
  },
  {
    "company": "Agfaphoto",
    "name": "Agfaphoto APX 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 25365,
    "description": "cheap panchromatic film with a classic emulsion that can be used universally and is suitable for a variety of applications",
    "launched": 2013,
    "datasheet": "datasheets/agfaphoto-apx-400.pdf",
    "lomography": "https://www.lomography.com/films/871910992-agfa-apx-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22APX%20400%22",
    "image": "agfaphoto-apx-400-135.png"
  },
  {
    "company": "Agfaphoto",
    "name": "Agfaphoto CT Precisa 100",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 2,
    "popularity": 23721,
    "description": "color reversal film similar to the Fujifilm Provia 100F",
    "launched": 2010,
    "datasheet": "datasheets/agfaphoto-ct-precisa-100.pdf",
    "lomography": "https://www.lomography.com/films/871960131-agfa-ct-precisa-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22CT%20Precisa%20100%22",
    "image": "agfaphoto-ct-precisa-100-135.png"
  },
  {
    "company": "Bergger",
    "name": "Bergger Pancro 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 0,
    "description": "panchromatic film with an extreme exposure latitude",
    "launched": 2017,
    "datasheet": "datasheets/bergger-pancro-400.pdf",
    "lomography": "https://www.lomography.com/films/871965009-bergger-pancro-400/photos",
    "flickr": "",
    "image": "bergger-pancro-400-120.png"
  },
  {
    "company": "Bergger",
    "name": "Bergger Pancro 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 4941,
    "description": "panchromatic film with an extreme exposure latitude",
    "launched": 2017,
    "datasheet": "datasheets/bergger-pancro-400.pdf",
    "lomography": "https://www.lomography.com/films/871965009-bergger-pancro-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Bergger%20Pancro%20400%22",
    "image": "bergger-pancro-400-135.png"
  },
  {
    "company": "Cinestillfilm",
    "name": "Cinestillfilm Cinestill 50D",
    "iso": "50",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 6009,
    "description": "film based on Kodaks Vision3 50D motion picture cinema film with removed rem-jet backing to allow C-41 processing",
    "launched": 2017,
    "datasheet": "datasheets/cinestillfilm-cinestill-50d.pdf",
    "lomography": "https://www.lomography.com/films/871961381-cinestill-50d/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Cinestill%2050D%22",
    "image": "cinestillfilm-cinestill-50d-120.png"
  },
  {
    "company": "Cinestillfilm",
    "name": "Cinestillfilm Cinestill 50D",
    "iso": "50",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 6009,
    "description": "film based on Kodaks Vision3 50D motion picture cinema film with removed rem-jet backing to allow C-41 processing",
    "launched": 2014,
    "datasheet": "datasheets/cinestillfilm-cinestill-50d.pdf",
    "lomography": "https://www.lomography.com/films/871961381-cinestill-50d/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Cinestill%2050D%22",
    "image": "cinestillfilm-cinestill-50d-135.png"
  },
  {
    "company": "Cinestillfilm",
    "name": "Cinestillfilm Cinestill 800T",
    "iso": "800",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 16462,
    "description": "film based on Kodak Vision3 500T motion picture cinema film with removed rem-jet backing to allow C-41 processing",
    "launched": 2017,
    "datasheet": "datasheets/cinestillfilm-cinestill-800t.pdf",
    "lomography": "https://www.lomography.com/films/871964831-cinestill-800t/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Cinestill%20800T%22",
    "image": "cinestillfilm-cinestill-800t-120.png"
  },
  {
    "company": "Cinestillfilm",
    "name": "Cinestillfilm Cinestill 800T",
    "iso": "800",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 16462,
    "description": "film based on Kodak Vision3 500T motion picture cinema film with removed rem-jet backing to allow C-41 processing",
    "launched": 2013,
    "datasheet": "datasheets/cinestillfilm-cinestill-800t.pdf",
    "lomography": "https://www.lomography.com/films/871964831-cinestill-800t/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Cinestill%20800T%22",
    "image": "cinestillfilm-cinestill-800t-135.png"
  },
  {
    "company": "Ferrania",
    "name": "Ferrania P30",
    "iso": "80",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 5880,
    "description": "a newly produced panchromatic film based on the historic cinema formula of the mid-20th century",
    "launched": 2017,
    "datasheet": "datasheets/ferrania-p30.pdf",
    "lomography": "https://www.lomography.com/films/871966128-ferrania-p30/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ferrania%20P30%22",
    "image": "ferrania-p30-135.png"
  },
  {
    "company": "Foma",
    "name": "Foma Fomapan 100",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 78873,
    "description": "very cheap panchromatic film with a classic emulsion. also known as Arista EDU Ultra B&W 100",
    "launched": 1995,
    "datasheet": "datasheets/foma-fomapan-100.pdf",
    "lomography": "https://www.lomography.com/films/871911862-fomapan-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fomapan%20100%22",
    "image": "foma-fomapan-100-120.png"
  },
  {
    "company": "Foma",
    "name": "Foma Fomapan 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 78873,
    "description": "very cheap panchromatic film with a classic emulsion. also known as Arista EDU Ultra B&W 100",
    "launched": 1995,
    "datasheet": "datasheets/foma-fomapan-100.pdf",
    "lomography": "https://www.lomography.com/films/871911862-fomapan-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fomapan%20100%22",
    "image": "foma-fomapan-100-135.png"
  },
  {
    "company": "Foma",
    "name": "Foma Fomapan 200",
    "iso": "200",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 32567,
    "description": "very cheap panchromatic film with a classic emulsion. also known as Arista EDU Ultra B&W 200",
    "launched": 1995,
    "datasheet": "datasheets/foma-fomapan-200.pdf",
    "lomography": "https://www.lomography.com/films/871913164-fomapan-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fomapan%20200%22",
    "image": "foma-fomapan-200-120.png"
  },
  {
    "company": "Foma",
    "name": "Foma Fomapan 200",
    "iso": "200",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 32567,
    "description": "very cheap panchromatic film with a classic emulsion. also known as Arista EDU Ultra B&W 200",
    "launched": 1995,
    "datasheet": "datasheets/foma-fomapan-200.pdf",
    "lomography": "https://www.lomography.com/films/871913164-fomapan-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fomapan%20200%22",
    "image": "foma-fomapan-200-135.png"
  },
  {
    "company": "Foma",
    "name": "Foma Fomapan 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 50575,
    "description": "very cheap panchromatic film with a classic emulsion. also known as Arista EDU Ultra B&W 400 and Holga 400",
    "launched": 1995,
    "datasheet": "datasheets/foma-fomapan-400.pdf",
    "lomography": "https://www.lomography.com/films/871912192-fomapan-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fomapan%20400%22",
    "image": "foma-fomapan-400-120.png"
  },
  {
    "company": "Foma",
    "name": "Foma Fomapan 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 50575,
    "description": "very cheap panchromatic film with a classic emulsion. also known as Arista EDU Ultra B&W 400 and Holga 400",
    "launched": 1995,
    "datasheet": "datasheets/foma-fomapan-400.pdf",
    "lomography": "https://www.lomography.com/films/871912192-fomapan-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fomapan%20400%22",
    "image": "foma-fomapan-400-135.png"
  },
  {
    "company": "Foma",
    "name": "Foma Fomapan R 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 196,
    "description": "panchromatic film with a clear base intended for reversal processing",
    "launched": 1995,
    "datasheet": "datasheets/foma-fomapan-r-100.pdf",
    "lomography": "https://www.lomography.com/films/871956777-fomapan-r-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fomapan%20R%20100%22",
    "image": "foma-fomapan-r-100-135.png"
  },
  {
    "company": "Foma",
    "name": "Foma Retropan 320",
    "iso": "320",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 2212,
    "description": "panchromatic film with a soft contrast",
    "launched": 2018,
    "datasheet": "datasheets/foma-retropan-320.pdf",
    "lomography": "https://www.lomography.com/films/871962399-foma-retropan-320/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Foma%20Retropan%20320%22",
    "image": "foma-retropan-320-120.png"
  },
  {
    "company": "Foma",
    "name": "Foma Retropan 320",
    "iso": "320",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 2212,
    "description": "panchromatic film with a soft contrast",
    "launched": 2015,
    "datasheet": "datasheets/foma-retropan-320.pdf",
    "lomography": "https://www.lomography.com/films/871962399-foma-retropan-320/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Foma%20Retropan%20320%22",
    "image": "foma-retropan-320-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Neopan Acros 100 II",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 3,
    "popularity": 33136,
    "description": "orthopanchromatic film with a modern emulsion and extreme resolution",
    "launched": 2019,
    "datasheet": "datasheets/fujifilm-neopan-acros-100.pdf",
    "lomography": "https://www.lomography.com/films/871946494-fuji-neopan-acros-100-120/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Neopan%20Acros%20100%22",
    "image": "fujifilm-neopan-acros-100-120.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Neopan Acros 100 II",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 33136,
    "description": "orthopanchromatic film with a modern emulsion and extreme resolution",
    "launched": 2019,
    "datasheet": "datasheets/fujifilm-neopan-acros-100.pdf",
    "lomography": "https://www.lomography.com/films/871923678-fuji-neopan-acros-100-35mm/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Neopan%20Acros%20100%22",
    "image": "fujifilm-neopan-acros-100-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm C200",
    "iso": "200",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 47740,
    "description": "cheap consumer film that can be used universally and is suitable for a variety of applications",
    "launched": 1990,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871962842-fuji-c200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20C200%22",
    "image": "fujifilm-c200-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Pro 160NS",
    "iso": "160",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 5732,
    "description": "professional film with excellent skin tone rendition and natural color reproduction",
    "launched": 2010,
    "datasheet": "datasheets/fujifilm-pro-160ns.pdf",
    "lomography": "https://www.lomography.com/films/871940322-fuji-160-ns/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Pro%20160NS%22",
    "image": "fujifilm-pro-160ns-120.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Pro 400H",
    "iso": "400",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 50045,
    "description": "professional film with excellent skin tone rendition and natural color reproduction",
    "launched": 2004,
    "datasheet": "datasheets/fujifilm-pro-400h.pdf",
    "lomography": "https://www.lomography.com/films/871912904-fuji-pro-400h/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Pro%20400H%22",
    "image": "fujifilm-pro-400h-120.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Pro 400H",
    "iso": "400",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 50045,
    "description": "professional film with excellent skin tone rendition and natural color reproduction",
    "launched": 2004,
    "datasheet": "datasheets/fujifilm-pro-400h.pdf",
    "lomography": "https://www.lomography.com/films/871912904-fuji-pro-400h/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Pro%20400H%22",
    "image": "fujifilm-pro-400h-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Provia 100F",
    "iso": "100",
    "format": "120",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 2,
    "popularity": 37437,
    "description": "film with extremely fine grain, vivid colors and extensive tone reproduction",
    "launched": 1999,
    "datasheet": "datasheets/fujifilm-provia-100f.pdf",
    "lomography": "https://www.lomography.com/films/871913190-fuji-provia-100f/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Provia%20100F%22",
    "image": "fujifilm-provia-100f-120.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Provia 100F",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 3,
    "popularity": 37437,
    "description": "film with extremely fine grain, vivid colors and extensive tone reproduction",
    "launched": 1999,
    "datasheet": "datasheets/fujifilm-provia-100f.pdf",
    "lomography": "https://www.lomography.com/films/871913190-fuji-provia-100f/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Provia%20100F%22",
    "image": "fujifilm-provia-100f-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Superia 200",
    "iso": "200",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 89128,
    "description": "cheap film that can be used universally and is suitable for a variety of applications",
    "launched": 2005,
    "datasheet": "datasheets/fujifilm-superia-200.pdf",
    "lomography": "https://www.lomography.com/films/871963412-fujifilm-superia-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Superia%20200%22",
    "image": "fujifilm-superia-200-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Superia X-TRA 400",
    "iso": "400",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 31819,
    "description": "consumer film for a variety of applications and super uniform fine grain technology",
    "launched": 2011,
    "datasheet": "datasheets/fujifilm-superia-x-tra-400.pdf",
    "lomography": "https://www.lomography.com/films/871922012-fujifilm-superia-x-tra-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Superia%20X-TRA%20400%22",
    "image": "fujifilm-superia-x-tra-400-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Velvia 50",
    "iso": "50",
    "format": "120",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 2,
    "popularity": 49101,
    "description": "legendary color reversal film with fine grain and very saturated colors",
    "launched": 2007,
    "datasheet": "datasheets/fujifilm-velvia-50.pdf",
    "lomography": "https://www.lomography.com/films/871953612-fuji-velvia-50/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Velvia%2050%22",
    "image": "fujifilm-velvia-50-120.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Velvia 50",
    "iso": "50",
    "format": "135",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 3,
    "popularity": 49101,
    "description": "legendary color reversal film with fine grain and very saturated colors",
    "launched": 2007,
    "datasheet": "datasheets/fujifilm-velvia-50.pdf",
    "lomography": "https://www.lomography.com/films/871953612-fuji-velvia-50/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Velvia%2050%22",
    "image": "fujifilm-velvia-50-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Velvia 100",
    "iso": "100",
    "format": "120",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 2,
    "popularity": 35174,
    "description": "legendary color reversal film with fine grain and very saturated colors",
    "launched": 2005,
    "datasheet": "datasheets/fujifilm-velvia-100.pdf",
    "lomography": "https://www.lomography.com/films/871962779-fuji-velvia-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Velvia%20100%22",
    "image": "fujifilm-velvia-100-120.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Velvia 100",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 3,
    "popularity": 35174,
    "description": "legendary color reversal film with fine grain and very saturated colors",
    "launched": 2005,
    "datasheet": "datasheets/fujifilm-velvia-100.pdf",
    "lomography": "https://www.lomography.com/films/871962779-fuji-velvia-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Velvia%20100%22",
    "image": "fujifilm-velvia-100-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Delta 100",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 76671,
    "description": "panchromatic film with a modern emulsion, a clear base, very fine grain and extreme contrast",
    "launched": 1992,
    "datasheet": "datasheets/ilford-delta-100.pdf",
    "lomography": "https://www.lomography.com/films/871926464-ilford-delta-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Delta%20100%22",
    "image": "ilford-delta-100-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Delta 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 76671,
    "description": "panchromatic film with a modern emulsion, very fine grain and extreme contrast",
    "launched": 1992,
    "datasheet": "datasheets/ilford-delta-100.pdf",
    "lomography": "https://www.lomography.com/films/871926464-ilford-delta-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Delta%20100%22",
    "image": "ilford-delta-100-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Delta 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 77632,
    "description": "panchromatic film with a modern emulsion, clear base, fine grain and high contrast",
    "launched": 1994,
    "datasheet": "datasheets/ilford-delta-400.pdf",
    "lomography": "https://www.lomography.com/films/871911584-ilford-delta-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Delta%20400%22",
    "image": "ilford-delta-400-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Delta 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 77632,
    "description": "panchromatic film with a modern emulsion, fine grain and high contrast",
    "launched": 1994,
    "datasheet": "datasheets/ilford-delta-400.pdf",
    "lomography": "https://www.lomography.com/films/871911584-ilford-delta-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Delta%20400%22",
    "image": "ilford-delta-400-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Delta 3200",
    "iso": "3200",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 46171,
    "description": "panchromatic film with a modern emulsion. the highest sensitivity black & white film available",
    "launched": 1998,
    "datasheet": "datasheets/ilford-delta-3200.pdf",
    "lomography": "https://www.lomography.com/films/871924744-ilford-delta-3200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Delta%203200%22",
    "image": "ilford-delta-3200-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Delta 3200",
    "iso": "3200",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 46171,
    "description": "panchromatic film with a modern emulsion. the highest sensitivity black & white film available",
    "launched": 1998,
    "datasheet": "datasheets/ilford-delta-3200.pdf",
    "lomography": "https://www.lomography.com/films/871924744-ilford-delta-3200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Delta%203200%22",
    "image": "ilford-delta-3200-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford FP4 Plus 125",
    "iso": "125",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 38388,
    "description": "panchromatic film with a classic emulsion, very fine grain and medium-high contrast",
    "launched": 1990,
    "datasheet": "datasheets/ilford-fp4-plus-125.pdf",
    "lomography": "https://www.lomography.com/films/871929575-ilford-fp4-plus-125/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20FP4%20Plus%22",
    "image": "ilford-fp4-plus-125-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford FP4 Plus 125",
    "iso": "125",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 38388,
    "description": "panchromatic film with a classic emulsion, very fine grain and medium-high contrast",
    "launched": 1990,
    "datasheet": "datasheets/ilford-fp4-plus-125.pdf",
    "lomography": "https://www.lomography.com/films/871929575-ilford-fp4-plus-125/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20FP4%20Plus%22",
    "image": "ilford-fp4-plus-125-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford HP5 Plus 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 85170,
    "description": "panchromatic film with a classic emulsion, fine grain and medium contrast",
    "launched": 1989,
    "datasheet": "datasheets/ilford-hp5-plus-400.pdf",
    "lomography": "https://www.lomography.com/films/871911956-ilford-hp5-plus-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20HP5%20Plus%22",
    "image": "ilford-hp5-plus-400-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford HP5 Plus 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 85170,
    "description": "panchromatic film with a classic emulsion, fine grain and medium contrast",
    "launched": 1989,
    "datasheet": "datasheets/ilford-hp5-plus-400.pdf",
    "lomography": "https://www.lomography.com/films/871911956-ilford-hp5-plus-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20HP5%20Plus%22",
    "image": "ilford-hp5-plus-400-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Ortho Plus 80",
    "iso": "80",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 2,
    "popularity": 1242,
    "description": "orthochromatic film with very fine grain, high resolution and contrast",
    "launched": 2019,
    "datasheet": "datasheets/ilford-ortho-plus-80.pdf",
    "lomography": "https://www.lomography.com/films/871969064-ilford-ortho-plus/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Ortho%20Plus%22",
    "image": "ilford-ortho-plus-80-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Ortho Plus 80",
    "iso": "80",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 2,
    "popularity": 1242,
    "description": "orthochromatic film with very fine grain, high resolution and contrast",
    "launched": 2019,
    "datasheet": "datasheets/ilford-ortho-plus-80.pdf",
    "lomography": "https://www.lomography.com/films/871969064-ilford-ortho-plus/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Ortho%20Plus%22",
    "image": "ilford-ortho-plus-80-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford PAN F Plus 50",
    "iso": "50",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 2,
    "popularity": 11925,
    "description": "panchromatic film with a classic emulsion, very fine grain, high resolution and contrast",
    "launched": 1992,
    "datasheet": "datasheets/ilford-pan-f-plus-50.pdf",
    "lomography": "https://www.lomography.com/films/871960967-ilford-pan-f-plus-50/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20PAN%20F%20Plus%2050%22",
    "image": "ilford-pan-f-plus-50-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford PAN F Plus 50",
    "iso": "50",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 2,
    "popularity": 11925,
    "description": "panchromatic film with a classic emulsion, very fine grain, high resolution and contrast",
    "launched": 1992,
    "datasheet": "datasheets/ilford-pan-f-plus-50.pdf",
    "lomography": "https://www.lomography.com/films/871960967-ilford-pan-f-plus-50/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20PAN%20F%20Plus%2050%22",
    "image": "ilford-pan-f-plus-50-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford SFX 200",
    "iso": "200",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 7807,
    "description": "superpanchromatic film for infrared style images (requires extra filter)",
    "launched": 2007,
    "datasheet": "datasheets/ilford-sfx-200.pdf",
    "lomography": "https://www.lomography.com/films/871922157-ilford-sfx-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20SFX%20200%22",
    "image": "ilford-sfx-200-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford SFX 200",
    "iso": "200",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 7807,
    "description": "superpanchromatic film for infrared style images (requires extra filter)",
    "launched": 2007,
    "datasheet": "datasheets/ilford-sfx-200.pdf",
    "lomography": "https://www.lomography.com/films/871922157-ilford-sfx-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20SFX%20200%22",
    "image": "ilford-sfx-200-135.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford XP2 super 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 37041,
    "description": "chromogenic film with extreme exposure latitude that can be developed using the C-41 process",
    "launched": 1998,
    "datasheet": "datasheets/ilford-xp2-super-400.pdf",
    "lomography": "https://www.lomography.com/films/871916608-ilford-xp2-super-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20XP2%20super%22",
    "image": "ilford-xp2-super-400-120.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford XP2 super 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 37041,
    "description": "chromogenic film with extreme exposure latitude that can be developed using the C-41 process",
    "launched": 1998,
    "datasheet": "datasheets/ilford-xp2-super-400.pdf",
    "lomography": "https://www.lomography.com/films/871916608-ilford-xp2-super-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20XP2%20super%22",
    "image": "ilford-xp2-super-400-135.png"
  },
  {
    "company": "JCH",
    "name": "JCH Street Pan 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 1830,
    "description": "superpanchromatic film, probably Agfa Aviphot Pan 400S",
    "launched": 2017,
    "datasheet": "datasheets/jch-street-pan-400.pdf",
    "lomography": "https://www.lomography.com/films/871964168-jch-street-pan-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22JCH%20Street%20Pan%22",
    "image": "jch-street-pan-400-120.png"
  },
  {
    "company": "JCH",
    "name": "JCH Street Pan 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 1830,
    "description": "superpanchromatic film, probably Agfa Aviphot Pan 400S",
    "launched": 2016,
    "datasheet": "datasheets/jch-street-pan-400.pdf",
    "lomography": "https://www.lomography.com/films/871964168-jch-street-pan-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22JCH%20Street%20Pan%22",
    "image": "jch-street-pan-400-135.png"
  },
  {
    "company": "Kentmere",
    "name": "Kentmere 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 22861,
    "description": "cheap panchromatic film with a classic emulsion",
    "launched": 2007,
    "datasheet": "datasheets/kentmere-100.pdf",
    "lomography": "https://www.lomography.com/films/871927949-kentmere-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kentmere%20100%22",
    "image": "kentmere-100-135.png"
  },
  {
    "company": "Kentmere",
    "name": "Kentmere 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 45323,
    "description": "cheap panchromatic film with a classic emulsion",
    "launched": 2007,
    "datasheet": "datasheets/kentmere-400.pdf",
    "lomography": "https://www.lomography.com/films/871925956-kentmere-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kentmere%20400%22",
    "image": "kentmere-400-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak ColorPlus 200",
    "iso": "200",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 97682,
    "description": "very cheap and popular consumer film. introduced as a cheaper alternative to the now also cheap Kodak Gold",
    "launched": 1990,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871917299-kodak-color-plus-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20ColorPlus%20200%22",
    "image": "kodak-colorplus-200-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Ektachrome E100",
    "iso": "100",
    "format": "120",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 3,
    "popularity": 3832,
    "description": "fine grain film with moderate saturation and neutral tones (based on the discontinued Ektachrome E100G)",
    "launched": 2019,
    "datasheet": "datasheets/kodak-ektachrome-e100.pdf",
    "lomography": "https://www.lomography.com/films/871911977-kodak-ektachrome-e100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Ektachrome%20E100%22",
    "image": "kodak-ektachrome-e100-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Ektachrome E100",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 3,
    "popularity": 3832,
    "description": "fine grain film with moderate saturation and neutral tones (based on the discontinued Ektachrome E100G)",
    "launched": 2018,
    "datasheet": "datasheets/kodak-ektachrome-e100.pdf",
    "lomography": "https://www.lomography.com/films/871911977-kodak-ektachrome-e100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Ektachrome%20E100%22",
    "image": "kodak-ektachrome-e100-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Ektar 100",
    "iso": "100",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 264882,
    "description": "the finest-grain color negative film available with high saturation and vivid colors",
    "launched": 2008,
    "datasheet": "datasheets/kodak-ektar-100.pdf",
    "lomography": "https://www.lomography.com/films/871912245-kodak-ektar-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Ektar%20100%22",
    "image": "kodak-ektar-100-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Ektar 100",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 264882,
    "description": "the finest-grain color negative film available with high saturation and vivid colors",
    "launched": 2008,
    "datasheet": "datasheets/kodak-ektar-100.pdf",
    "lomography": "https://www.lomography.com/films/871912245-kodak-ektar-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Ektar%20100%22",
    "image": "kodak-ektar-100-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Gold 200",
    "iso": "200",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 153505,
    "description": "cheap and popular consumer film",
    "launched": 2007,
    "datasheet": "datasheets/kodak-gold-200.pdf",
    "lomography": "https://www.lomography.com/films/871958647-kodak-gold-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Gold%20200%22",
    "image": "kodak-gold-200-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Portra 160",
    "iso": "160",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 142029,
    "description": "professional film with natural skin tone reproduction",
    "launched": 2011,
    "datasheet": "datasheets/kodak-portra-160.pdf",
    "lomography": "https://www.lomography.com/films/871916076-kodak-portra-160/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Portra%20160%22",
    "image": "kodak-portra-160-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Portra 160",
    "iso": "160",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 142029,
    "description": "professional film with natural skin tone reproduction",
    "launched": 2011,
    "datasheet": "datasheets/kodak-portra-160.pdf",
    "lomography": "https://www.lomography.com/films/871916076-kodak-portra-160/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Portra%20160%22",
    "image": "kodak-portra-160-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Portra 400",
    "iso": "400",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 247488,
    "description": "professional film with natural skin tone reproduction",
    "launched": 2010,
    "datasheet": "datasheets/kodak-portra-400.pdf",
    "lomography": "https://www.lomography.com/films/871910984-kodak-portra-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Portra%20400%22",
    "image": "kodak-portra-400-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Portra 400",
    "iso": "400",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 247488,
    "description": "professional film with natural skin tone reproduction",
    "launched": 2010,
    "datasheet": "datasheets/kodak-portra-400.pdf",
    "lomography": "https://www.lomography.com/films/871910984-kodak-portra-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Portra%20400%22",
    "image": "kodak-portra-400-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Portra 800",
    "iso": "800",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 36210,
    "description": "professional film with natural skin tone reproduction",
    "launched": 2006,
    "datasheet": "datasheets/kodak-portra-800.pdf",
    "lomography": "https://www.lomography.com/films/871920252-kodak-portra-800/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Portra%20800%22",
    "image": "kodak-portra-800-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Portra 800",
    "iso": "800",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 36210,
    "description": "professional film with natural skin tone reproduction",
    "launched": 2006,
    "datasheet": "datasheets/kodak-portra-800.pdf",
    "lomography": "https://www.lomography.com/films/871920252-kodak-portra-800/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20Portra%20800%22",
    "image": "kodak-portra-800-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak T-MAX 100",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 31840,
    "description": "panchromatic film with a modern emulsion and a very high resolution",
    "launched": 2002,
    "datasheet": "datasheets/kodak-t-max-100.pdf",
    "lomography": "https://www.lomography.com/films/871912688-kodak-t-max-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20T-MAX%20100%22",
    "image": "kodak-t-max-100-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak T-MAX 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 31840,
    "description": "panchromatic film with a modern emulsion and a very high resolution",
    "launched": 2002,
    "datasheet": "datasheets/kodak-t-max-100.pdf",
    "lomography": "https://www.lomography.com/films/871912688-kodak-t-max-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20T-MAX%20100%22",
    "image": "kodak-t-max-100-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak T-MAX 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 53823,
    "description": "panchromatic film with a modern emulsion and a very high resolution",
    "launched": 2007,
    "datasheet": "datasheets/kodak-t-max-400.pdf",
    "lomography": "https://www.lomography.com/films/871912064-kodak-t-max-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20T-MAX%20400%22",
    "image": "kodak-t-max-400-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak T-MAX 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 53823,
    "description": "panchromatic film with a modern emulsion and a very high resolution",
    "launched": 2007,
    "datasheet": "datasheets/kodak-t-max-400.pdf",
    "lomography": "https://www.lomography.com/films/871912064-kodak-t-max-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20T-MAX%20400%22",
    "image": "kodak-t-max-400-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak T-MAX P3200",
    "iso": "3200",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "modern",
    "price": 2,
    "popularity": 2804,
    "description": "panchromatic film with a modern emulsion",
    "launched": 2018,
    "datasheet": "datasheets/kodak-t-max-p-3200.pdf",
    "lomography": "https://www.lomography.com/films/871933147-kodak-t-max-p3200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20T-MAX%20P3200%22",
    "image": "kodak-t-max-p-3200-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak TRI-X 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 2,
    "popularity": 170104,
    "description": "iconic panchromatic film with a classic emulsion",
    "launched": 2007,
    "datasheet": "datasheets/kodak-tri-x-400.pdf",
    "lomography": "https://www.lomography.com/films/871911232-kodak-tri-x-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20TRI-X%20400%22",
    "image": "kodak-tri-x-400-120.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak TRI-X 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 2,
    "popularity": 170104,
    "description": "iconic panchromatic film with a classic emulsion",
    "launched": 2007,
    "datasheet": "datasheets/kodak-tri-x-400.pdf",
    "lomography": "https://www.lomography.com/films/871911232-kodak-tri-x-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20TRI-X%20400%22",
    "image": "kodak-tri-x-400-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Pro Image 100",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 21802,
    "description": "budget color film with neutral skin tones for portraits, weddings and social events",
    "launched": 1997,
    "datasheet": "datasheets/kodak-proimage-100.pdf",
    "lomography": "https://www.lomography.com/films/871961799-kodak-proimage-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20ProImage%20100%22",
    "image": "kodak-proimage-100-135.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak UltraMax 400",
    "iso": "400",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 98624,
    "description": "consumer film that can be used universally and is suitable for a variety of applications",
    "launched": 2007,
    "datasheet": "datasheets/kodak-ultramax-400.pdf",
    "lomography": "https://www.lomography.com/films/871945457-kodak-ultramax-400-35mm/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kodak%20UltraMax%20400%22",
    "image": "kodak-ultramax-400-135.png"
  },
  {
    "company": "Kosmo",
    "name": "Kosmo Foto Mono 100",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 2720,
    "description": "probably Fomo Fomapan 100 with a nice retro packaging",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871966555-kosmo-foto-mono-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kosmo%20Foto%20Mono%22",
    "image": "kosmo-foto-mono-100-120.png"
  },
  {
    "company": "Kosmo",
    "name": "Kosmo Foto Mono 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 2720,
    "description": "probably Fomo Fomapan 100 with a nice retro packaging",
    "launched": 2017,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871966555-kosmo-foto-mono-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Kosmo%20Foto%20Mono%22",
    "image": "kosmo-foto-mono-100-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Berlin 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 558,
    "description": "cinematic panchromatic film with wide exposure latitude, probably a rebranded version of Orwo N74+",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871967606-lomography-berlin-kino-400-iso/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Berlin%20400%22",
    "image": "lomography-berlin-400-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Berlin 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 558,
    "description": "cinematic panchromatic film with wide exposure latitude, probably a rebranded version of Orwo N74+",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871967606-lomography-berlin-kino-400-iso/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Berlin%20400%22",
    "image": "lomography-berlin-400-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Color Negative 100",
    "iso": "100",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 4861,
    "description": "general purpose color film, probably Kodak Gold 100",
    "launched": 2009,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871910961-lomography-color-negative-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Color%20Negative%20100%22",
    "image": "lomography-color-negative-100-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Color Negative 100",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 4861,
    "description": "general purpose color film, probably Kodak Gold 100",
    "launched": 2009,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871910961-lomography-color-negative-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Color%20Negative%20100%22",
    "image": "lomography-color-negative-100-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Color Negative 400",
    "iso": "400",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 9092,
    "description": "general purpose color film",
    "launched": 2009,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871962160-lomography-color-negative-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Color%20Negative%20400%22",
    "image": "lomography-color-negative-400-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Color Negative 400",
    "iso": "400",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 9092,
    "description": "general purpose color film",
    "launched": 2009,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871962160-lomography-color-negative-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Color%20Negative%20400%22",
    "image": "lomography-color-negative-400-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Color Negative 800",
    "iso": "800",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 4622,
    "description": "general purpose color film",
    "launched": 2009,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871921449-lomography-color-negative-800/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Color%20Negative%20800%22",
    "image": "lomography-color-negative-800-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Color Negative 800",
    "iso": "800",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 4622,
    "description": "general purpose color film",
    "launched": 2009,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871921449-lomography-color-negative-800/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Color%20Negative%20800%22",
    "image": "lomography-color-negative-800-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Earl Grey 100",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 2858,
    "description": "general purpose panchromatic film, probably Foma Fomapan 100",
    "launched": 2011,
    "datasheet": "datasheets/lomography-earl-grey-100.pdf",
    "lomography": "https://www.lomography.com/films/871942379-lomography-earl-grey-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Earl%20Grey%22",
    "image": "lomography-earl-grey-100-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Earl Grey 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 2858,
    "description": "general purpose panchromatic film, probably Foma Fomapan 100",
    "launched": 2011,
    "datasheet": "datasheets/lomography-earl-grey-100.pdf",
    "lomography": "https://www.lomography.com/films/871942379-lomography-earl-grey-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Earl%20Grey%22",
    "image": "lomography-earl-grey-100-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lady Grey 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 4860,
    "description": "general purpose panchromatic film, probably Foma Fomapan 400",
    "launched": 2011,
    "datasheet": "datasheets/lomography-lady-grey-400.pdf",
    "lomography": "https://www.lomography.com/films/871963407-lomography-lady-grey-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lady%20Grey%22",
    "image": "lomography-lady-grey-400-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lady Grey 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 4860,
    "description": "general purpose panchromatic film, probably Foma Fomapan 400",
    "launched": 2011,
    "datasheet": "datasheets/lomography-lady-grey-400.pdf",
    "lomography": "https://www.lomography.com/films/871963407-lomography-lady-grey-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lady%20Grey%22",
    "image": "lomography-lady-grey-400-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lobster 200",
    "iso": "200",
    "format": "110",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 263,
    "description": "creative redscale film with an extended exposure range",
    "launched": 2012,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871962641-lomography-110-lobster/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lobster%22",
    "image": "lomography-lobster-200-110.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomochrome Metropolis 100-400",
    "iso": "200",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 114,
    "description": "film with very desaturated colors",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871968570-lomochrome-metropolis-xr-100-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lomochrome%20Metropolis%22",
    "image": "lomography-lomochrome-metropolis-100-400-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomochrome Metropolis 100-400",
    "iso": "200",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 114,
    "description": "film with very desaturated colors",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871968570-lomochrome-metropolis-xr-100-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lomochrome%20Metropolis%22",
    "image": "lomography-lomochrome-metropolis-100-400-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomochrome Metropolis 100-400",
    "iso": "200",
    "format": "110",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 114,
    "description": "film with very desaturated colors",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871968570-lomochrome-metropolis-xr-100-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lomochrome%20Metropolis%22",
    "image": "lomography-lomochrome-metropolis-100-400-110.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomochrome Purple 100-400",
    "iso": "200",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 1698,
    "description": "creative film with a strong purple tint",
    "launched": 2013,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871963650-lomography-lomochrome-purple-xr-100-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lomochrome%20Purple%22",
    "image": "lomography-lomochrome-purple-100-400-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomochrome Purple 100-400",
    "iso": "200",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 1698,
    "description": "creative film with a strong purple tint",
    "launched": 2013,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871963650-lomography-lomochrome-purple-xr-100-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lomochrome%20Purple%22",
    "image": "lomography-lomochrome-purple-100-400-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomochrome Purple 100-400",
    "iso": "200",
    "format": "110",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 1698,
    "description": "creative film with a strong purple tint",
    "launched": 2020,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871963650-lomography-lomochrome-purple-xr-100-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Lomochrome%20Purple%22",
    "image": "lomography-lomochrome-purple-100-400-110.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Orca 100",
    "iso": "100",
    "format": "110",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 1686,
    "description": "general purpose panchromatic film",
    "launched": 2012,
    "datasheet": "datasheets/lomography-orca-100.pdf",
    "lomography": "https://www.lomography.com/films/871949443-lomography-orca-100-b-w-110/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Orca%22",
    "image": "lomography-orca-100-110.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Peacock 200",
    "iso": "200",
    "format": "110",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 2,
    "popularity": 376,
    "description": "color slide film meant for cross-processing",
    "launched": 2013,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871955282-lomography-peacock-x-pro-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Peacock%22",
    "image": "lomography-peacock-200-110.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Potsdam 100",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 463,
    "description": "cinematic panchromatic film with fine grain, probably a rebranded version of Orwo N54",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871968638-lomography-potsdam-kino-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Potsdam%20100%22",
    "image": "lomography-potsdam-100-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Potsdam 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 463,
    "description": "cinematic panchromatic film with fine grain, probably a rebranded version of Orwo N54",
    "launched": 2019,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871968638-lomography-potsdam-kino-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Potsdam%20100%22",
    "image": "lomography-potsdam-100-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Redscale 50-200",
    "iso": "100",
    "format": "120",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 2,
    "popularity": 16469,
    "description": "creative redscale film with an extended exposure range",
    "launched": 2008,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871961386-lomography-redscale-xr-50-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Redscale%22",
    "image": "lomography-redscale-50-200-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Redscale 50-200",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 16469,
    "description": "creative redscale film with an extended exposure range",
    "launched": 2008,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871961386-lomography-redscale-xr-50-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Redscale%22",
    "image": "lomography-redscale-50-200-135.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Tiger 200",
    "iso": "200",
    "format": "110",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 1,
    "popularity": 418,
    "description": "general purpose color film",
    "launched": 2012,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871949468-lomography-color-tiger-200-110/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Lomography%20Tiger%20200%22",
    "image": "lomography-tiger-200-110.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Crossbird",
    "iso": "200",
    "format": "120",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 2,
    "popularity": 3302,
    "description": "intended to be cross-developed as a color negative film, based on Agfa RSX200",
    "launched": 2018,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871924483-rollei-crossbird/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Crossbird%22",
    "image": "rollei-crossbird-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Crossbird",
    "iso": "200",
    "format": "135",
    "color": "color",
    "type": "slide",
    "emulsion": "",
    "price": 2,
    "popularity": 3302,
    "description": "intended to be cross-developed as a color negative film, based on Agfa RSX200",
    "launched": 2018,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871924483-rollei-crossbird/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Crossbird%22",
    "image": "rollei-crossbird-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Infrared 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 2805,
    "description": "superpanchromatic film with transparent base for infrared images, probably Agfa Aviphot Pan 400",
    "launched": 0,
    "datasheet": "datasheets/rollei-infrared-400.pdf",
    "lomography": "https://www.lomography.com/films/871913788-rollei-infrared-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Infrared%20400%22",
    "image": "rollei-infrared-400-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Infrared 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 2805,
    "description": "superpanchromatic film with transparent base for infrared images, probably Agfa Aviphot Pan 400",
    "launched": 0,
    "datasheet": "datasheets/rollei-infrared-400.pdf",
    "lomography": "https://www.lomography.com/films/871913788-rollei-infrared-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Infrared%20400%22",
    "image": "rollei-infrared-400-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Ortho 25",
    "iso": "25",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 2505,
    "description": "orthochromatic film with a clear base, fine grain and high contrast",
    "launched": 2017,
    "datasheet": "datasheets/rollei-ortho-25.pdf",
    "lomography": "https://www.lomography.com/films/871966115-rollei-ortho-25/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Ortho%2025%22",
    "image": "rollei-ortho-25-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Ortho 25",
    "iso": "25",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 2505,
    "description": "orthochromatic film with a clear base, fine grain and high contrast",
    "launched": 2017,
    "datasheet": "datasheets/rollei-ortho-25.pdf",
    "lomography": "https://www.lomography.com/films/871966115-rollei-ortho-25/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Ortho%2025%22",
    "image": "rollei-ortho-25-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Retro 80S",
    "iso": "80",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 15184,
    "description": "superpanchromatic film, probably Agfa Aviphot Pan 80",
    "launched": 0,
    "datasheet": "datasheets/rollei-retro-80s.pdf",
    "lomography": "https://www.lomography.com/films/871930991-rollei-retro-80s/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Retro%2080S%22",
    "image": "rollei-retro-80s-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Retro 80S",
    "iso": "80",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 15184,
    "description": "superpanchromatic film, probably Agfa Aviphot Pan 80",
    "launched": 0,
    "datasheet": "datasheets/rollei-retro-80s.pdf",
    "lomography": "https://www.lomography.com/films/871930991-rollei-retro-80s/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Retro%2080S%22",
    "image": "rollei-retro-80s-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Retro 400S",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 17373,
    "description": "superpanchromatic film, probably Agfa Aviphot Pan 400",
    "launched": 0,
    "datasheet": "datasheets/rollei-retro-400s.pdf",
    "lomography": "https://www.lomography.com/films/871919398-rollei-retro-400s/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Retro%20400S%22",
    "image": "rollei-retro-400s-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Retro 400S",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 17373,
    "description": "superpanchromatic film, probably Agfa Aviphot Pan 400",
    "launched": 0,
    "datasheet": "datasheets/rollei-retro-400s.pdf",
    "lomography": "https://www.lomography.com/films/871919398-rollei-retro-400s/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Retro%20400S%22",
    "image": "rollei-retro-400s-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei RPX 25",
    "iso": "25",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 3931,
    "description": "panchromatic film with a classic emulsion and very high resolution",
    "launched": 2014,
    "datasheet": "datasheets/rollei-rpx-25.pdf",
    "lomography": "https://www.lomography.com/films/871959684-rollei-rpx-25/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20RPX%2025%22",
    "image": "rollei-rpx-25-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei RPX 25",
    "iso": "25",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 3931,
    "description": "panchromatic film with a classic emulsion and very high resolution",
    "launched": 2014,
    "datasheet": "datasheets/rollei-rpx-25.pdf",
    "lomography": "https://www.lomography.com/films/871959684-rollei-rpx-25/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20RPX%2025%22",
    "image": "rollei-rpx-25-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei RPX 100",
    "iso": "100",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 9429,
    "description": "panchromatic film with a classic emulsion",
    "launched": 2014,
    "datasheet": "datasheets/rollei-rpx-100.pdf",
    "lomography": "https://www.lomography.com/films/871963108-rollei-rpx-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20RPX%20100%22",
    "image": "rollei-rpx-100-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei RPX 100",
    "iso": "100",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 9429,
    "description": "panchromatic film with a classic emulsion",
    "launched": 2014,
    "datasheet": "datasheets/rollei-rpx-100.pdf",
    "lomography": "https://www.lomography.com/films/871963108-rollei-rpx-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20RPX%20100%22",
    "image": "rollei-rpx-100-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei RPX 400",
    "iso": "400",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 13469,
    "description": "panchromatic film with a classic emulsion",
    "launched": 2014,
    "datasheet": "datasheets/rollei-rpx-400.pdf",
    "lomography": "https://www.lomography.com/films/871934897-rollei-rpx-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20RPX%20400%22",
    "image": "rollei-rpx-400-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei RPX 400",
    "iso": "400",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 13469,
    "description": "panchromatic film with a classic emulsion",
    "launched": 2014,
    "datasheet": "datasheets/rollei-rpx-400.pdf",
    "lomography": "https://www.lomography.com/films/871934897-rollei-rpx-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20RPX%20400%22",
    "image": "rollei-rpx-400-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Superpan 200",
    "iso": "200",
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 9708,
    "description": "superpanchromatic film. probably Agfa Aviphot Pan 200",
    "launched": 0,
    "datasheet": "datasheets/rollei-superpan-200.pdf",
    "lomography": "https://www.lomography.com/films/871957145-rollei-superpan-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Superpan%20200%22",
    "image": "rollei-superpan-200-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Superpan 200",
    "iso": "200",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 9708,
    "description": "superpanchromatic film. probably Agfa Aviphot Pan 200",
    "launched": 0,
    "datasheet": "datasheets/rollei-superpan-200.pdf",
    "lomography" : "https://www.lomography.com/films/871957145-rollei-superpan-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Superpan%20200%22",
    "image": "rollei-superpan-200-135.png"
  }
]