var discontinuedfilms = [
  {
    "company": "Adox",
    "name": "Adox Color Implosion",
    "iso": "100",
    "format": "135",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 2,
    "popularity": 5065,
    "description": "film with a partially collapsed color coupling system for unpredictable results. effective speed is ISO 100",
    "launched": 2012,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871951418-adox-color-implosion/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20Color%20Implosion%22",
    "image": "adox-color-implosion-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox Scala 160",
    "iso": 160,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 425,
    "description": "panchromatic film with a clear base intended for reversal processing",
    "launched": 2016,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871965587-adox-scala-160/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20Scala%20160%22",
    "image": "adox-scala-160-135.png"
  },
  {
    "company": "Adox",
    "name": "Adox Silvermax 100",
    "iso": 100,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "classic",
    "price": 1,
    "popularity": 5273,
    "description": "orthopanchromatic film with a classic emulsion, a clear base and an extreme exposure latitude",
    "launched": 2012,
    "datasheet": "datasheets/adox-silvermax-100.pdf",
    "lomography": "https://www.lomography.com/films/871953394-adox-silvermax-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Adox%20Silvermax%20100%22",
    "image": "adox-silvermax-100-135.png"
  },
  {
    "company": "Agfaphoto",
    "name": "Agfaphoto CT Precisa 100",
    "iso": 100,
    "format": "135",
    "color": "color",
    "type": "(E-6)",
    "emulsion": "",
    "price": 2,
    "popularity": 21250,
    "description": "color reversal film similar to the Fujifilm Provia 100F",
    "launched": 2010,
    "datasheet": "datasheets/agfaphoto-ct-precisa-100.pdf",
    "lomography": "https://www.lomography.com/films/871960131-agfa-ct-precisa-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22CT%20Precisa%20100%22",
    "image": "agfaphoto-ct-precisa-100-135.png"
  },
  {
    "company": "Film Washi",
    "name": "Film Washi A 12",
    "iso": 12,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 81,
    "description": "orthochromatic film, originally intended as leader and protection during the reproduction process of motion picture films",
    "launched": 2015,
    "datasheet": "datasheets/film-washi-a-12.pdf",
    "lomography": "https://www.lomography.com/films/871966360-film-washi-a/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Film%20Washi%20A%22",
    "image": "film-washi-a-12-135.png"
  },
  {
    "company": "Film Washi",
    "name": "Film Washi D 500",
    "iso": 500,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 155,
    "description": "panchromatic aerial surveillance film",
    "launched": 2015,
    "datasheet": "datasheets/film-washi-d-500.pdf",
    "lomography": "https://www.lomography.com/films/871963252-film-washi-d/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Film%20Washi%20D%22",
    "image": "film-washi-d-500-135.png"
  },
  {
    "company": "Film Washi",
    "name": "Film Washi I 80",
    "iso": 80,
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 4,
    "description": "orthochromatic industrial X-ray film without anti-halation layer",
    "launched": 2021,
    "datasheet": "datasheets/film-washi-i-80.pdf",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Film%20Washi%20I%22",
    "image": "film-washi-i-80-120.png"
  },
  {
    "company": "Film Washi",
    "name": "Film Washi R 100",
    "iso": 100,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 3,
    "popularity": 0,
    "description": "reversal black & white panchromatic paper for photo booths",
    "launched": 2020,
    "datasheet": "datasheets/film-washi-r-100.pdf",
    "lomography": "",
    "flickr": "",
    "image": "film-washi-r-100-135.png"
  },
  {
    "company": "Film Washi",
    "name": "Film Washi S 50",
    "iso": 50,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 357,
    "description": "panchromatic film, originally intended for sound recording",
    "launched": 2015,
    "datasheet": "datasheets/film-washi-s-50.pdf",
    "lomography": "https://www.lomography.com/films/871963226-film-washi-s/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Film%20Washi%20S%22",
    "image": "film-washi-s-50-135.png"
  },
  {
    "company": "Film Washi",
    "name": "Film Washi S 50",
    "iso": 50,
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 357,
    "description": "panchromatic film, originally intended for sound recording",
    "launched": 2018,
    "datasheet": "datasheets/film-washi-s-50.pdf",
    "lomography": "https://www.lomography.com/films/871963226-film-washi-s/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Film%20Washi%20S%22",
    "image": "film-washi-s-50-120.png"
  },
  {
    "company": "Film Washi",
    "name": "Film Washi X",
    "iso": "",
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 0,
    "popularity": 0,
    "description": "",
    "launched": 2015,
    "datasheet": "",
    "lomography": "",
    "flickr": "",
    "image": "film-washi-x-400-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Pro 160NS",
    "iso": 160,
    "format": "120",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 2,
    "popularity": 5798,
    "description": "professional film with excellent skin tone rendition and natural color reproduction",
    "launched": 2010,
    "datasheet": "datasheets/fujifilm-pro-160ns.pdf",
    "lomography": "https://www.lomography.com/films/871940322-fuji-160-ns/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Pro%20160NS%22",
    "image": "fujifilm-pro-160ns-120.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Pro 400H",
    "iso": 400,
    "format": "135",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 2,
    "popularity": 43485,
    "description": "professional film with excellent skin tone rendition and natural color reproduction",
    "launched": 2004,
    "datasheet": "datasheets/fujifilm-pro-400h.pdf",
    "lomography": "https://www.lomography.com/films/871912904-fuji-pro-400h/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Pro%20400H%22",
    "image": "fujifilm-pro-400h-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Superia 200",
    "iso": 200,
    "format": "135",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 1,
    "popularity": 75476,
    "description": "cheap film that can be used universally and is suitable for a variety of applications",
    "launched": 2005,
    "datasheet": "datasheets/fujifilm-superia-200.pdf",
    "lomography": "https://www.lomography.com/films/871963412-fujifilm-superia-200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Superia%20200%22",
    "image": "fujifilm-superia-200-135.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm Superia Venus 800",
    "iso": "800",
    "format": "135",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 3,
    "popularity": 2055,
    "description": "high ISO film that is primarily targeted at the japanese market",
    "launched": 0,
    "datasheet": "datasheets/fujifilm-superia-venus-800.pdf",
    "lomography": "https://www.lomography.com/films/871939313-fujifilm-superia-venus-800/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Fuji%20Superia%20Venus%20800%22",
    "image": "images/fujifilm-superia-venus-800-135.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Crossbird",
    "iso": 200,
    "format": "120",
    "color": "color",
    "type": "(E-6)",
    "emulsion": "",
    "price": 2,
    "popularity": 3302,
    "description": "intended to be cross-developed as a color negative film, based on Agfa RSX200",
    "launched": 2018,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871924483-rollei-crossbird/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Crossbird%22",
    "image": "rollei-crossbird-120.png"
  },
  {
    "company": "Rollei",
    "name": "Rollei Crossbird",
    "iso": 200,
    "format": "135",
    "color": "color",
    "type": "(E-6)",
    "emulsion": "",
    "price": 2,
    "popularity": 3302,
    "description": "intended to be cross-developed as a color negative film, based on Agfa RSX200",
    "launched": 2018,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871924483-rollei-crossbird/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Rollei%20Crossbird%22",
    "image": "rollei-crossbird-135.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra 52XX",
    "iso": 200,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 36,
    "description": "panchromatic film, respooled motion picture cinema film Kodak Double-X 5222",
    "launched": 2018,
    "datasheet": "datasheets/kodak-eastman-double-x.pdf",
    "lomography": "https://www.lomography.com/films/871968781-silberra-cinema-52xx-asa200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%2052XX%22",
    "image": "random.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra 54UN",
    "iso": 100,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 0,
    "description": "panchromatic film motion picture cinema film, Orwo UN54",
    "launched": 2018,
    "datasheet": "",
    "lomography": "",
    "flickr": "",
    "image": "random.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra 74N+",
    "iso": 400,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 3,
    "description": "panchromatic motion picture cinema film, Orwo N74+",
    "launched": 2019,
    "datasheet": "",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%2074N+%22",
    "image": "random.png"
  },
  
  {
    "company": "Silberra",
    "name": "Silberra Orta 50",
    "iso": 50,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 47,
    "description": "orthochromatic film, designed for optical printing",
    "launched": 2018,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871970188-silberra-orta-50/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20Orta%2050%22",
    "image": "silberra-orta-50-135.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra Pan 100",
    "iso": 100,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 167,
    "description": "panchromatic film, based on Agfa surveillance film",
    "launched": 2017,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871965956-silberra-pan-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20Pan%20100%22",
    "image": "silberra-pan-100-135.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra Pan 160",
    "iso": 160,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 161,
    "description": "panchromatic film, based on Agfa surveillance film",
    "launched": 2017,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871966407-silberra-pan160/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20Pan%20160%22",
    "image": "silberra-pan-160-135.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra Pan 200",
    "iso": 200,
    "format": "120",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 57,
    "description": "panchromatic film, based on Agfa surveillance film",
    "launched": 2021,
    "datasheet": "",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20Pan%20200%22",
    "image": "silberra-pan-200-120.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra Pan 200",
    "iso": 200,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 57,
    "description": "panchromatic film, based on Agfa surveillance film",
    "launched": 2017,
    "datasheet": "",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20Pan%20200%22",
    "image": "random.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra Pan 50",
    "iso": 50,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 148,
    "description": "panchromatic film, based on Agfa surveillance film",
    "launched": 2017,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871966923-silberra-pan50/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20Pan%2050%22",
    "image": "silberra-pan-50-135.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra S25",
    "iso": 25,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 38,
    "description": "superpanchromatic film with a high resolution",
    "launched": 2020,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871970901-silberra-s25/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20S25%22",
    "image": "silberra-s25-135.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra U200",
    "iso": 200,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 161,
    "description": "film with a mix of classic and modern grain and a transparent base",
    "launched": 2018,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871968084-silberra-u200/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20U200%22",
    "image": "silberra-u200-135.png"
  },
  {
    "company": "Silberra",
    "name": "Silberra U400",
    "iso": 400,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 53,
    "description": "film with a mix of classic and modern grain and a transparent base",
    "launched": 2018,
    "datasheet": "",
    "lomography": "https://www.lomography.com/films/871969182-silberra-u400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Silberra%20U400%22",
    "image": "silberra-u400-135.png"
  },
  {
    "company": "Street Candy",
    "name": "Street Candy ATM 400",
    "iso": 400,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 228,
    "description": "panchromatic film, intended for surveillance cameras, probably a rebranded version of Ilford HP5 Plus",
    "launched": 2018,
    "datasheet": "datasheets/street-candy-atm-400.pdf",
    "lomography": "https://www.lomography.com/films/871967677-street-candy-atm-400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Street%20Candy%20ATM%20400%22",
    "image": "street-candy-atm-400-135.png"
  }
]
