var futurefilms = [
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo DN21",
    "iso": 16,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 57,
    "description": "panchromatic duplicating negative film with a clear base",
    "launched": 2010,
    "datasheet": "datasheets/orwo-dn21.pdf",
    "lomography": "https://www.lomography.de/films/871971058-orwo-dn21/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20DN21%22",
    "image": "random.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo DP31",
    "iso": 8,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 71,
    "description": "panchromatic duplicating positive film with a clear base",
    "launched": 2010,
    "datasheet": "datasheets/orwo-dp31.pdf",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20DP31%22",
    "image": "random.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo NC400",
    "iso": 400,
    "format": "135",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 3,
    "popularity": 38,
    "description": "motion picture cinema film with a bluish tint",
    "launched": 2022,
    "datasheet": "datasheets/orwo-nc400.pdf",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20NC400%22",
    "image": "orwo-nc400-135.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo P400",
    "iso": 400,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 140,
    "description": "",
    "launched": 2024,
    "datasheet": "datasheets/orwo-p400.pdf",
    "lomography": "https://www.lomography.de/films/871972154-orwo-p400/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20P400%22",
    "image": "random.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo PF2",
    "iso": 3,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 90,
    "description": "fine grain orthochromatic film with a transparent film base",
    "launched": 2010,
    "datasheet": "datasheets/orwo-pf2.pdf",
    "lomography": "https://www.lomography.de/films/871947407-orwo-pf2/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20PF2%22",
    "image": "random.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo UN54",
    "iso": 100,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 6529,
    "description": "panchromatic motion picture cinema film",
    "launched": 2022,
    "datasheet": "datasheets/orwo-un54.pdf",
    "lomography": "https://www.lomography.de/films/871952973-orwo-un54/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20UN54%22",
    "image": "random.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Ilfocolor 400 Cine Tone",
    "iso": 400,
    "format": "135",
    "color": "color",
    "type": "(ECN-2)",
    "emulsion": "",
    "price": 3,
    "popularity": 0,
    "description": "could be Kodak Vision3 250D",
    "launched": 2023,
    "datasheet": "",
    "lomography": "",
    "flickr": "",
    "image": "random.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Ilfocolor 400 Vintage Tone",
    "iso": 400,
    "format": "135",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 3,
    "popularity": 90,
    "description": "likely Orwo NC500",
    "launched": 2023,
    "datasheet": "",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Ilford%20Ilfocolor%20400%22%20Vintage",
    "image": "random.png"
  },
  {
    "company": "KONO!",
    "name": "KONO! Color 400",
    "iso": 400,
    "format": "135",
    "color": "color",
    "type": "(C-41)",
    "emulsion": "",
    "price": 2,
    "popularity": 0,
    "description": "",
    "launched": 2023,
    "datasheet": "",
    "lomography": "",
    "flickr": "",
    "image": "random.png"
  }
]
