var futurefilms = [
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo DN21",
    "iso": 16,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 57,
    "description": "panchromatic duplicating negative film with a clear base",
    "launched": 2010,
    "datasheet": "datasheets/orwo-dn21.pdf",
    "lomography": "https://www.lomography.de/films/871971058-orwo-dn21/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20DN21%22",
    "image": "random.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo DP31",
    "iso": 8,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 71,
    "description": "panchromatic duplicating positive film with a clear base",
    "launched": 2010,
    "datasheet": "datasheets/orwo-dp31.pdf",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20DP31%22",
    "image": "random.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo NC400",
    "iso": 400,
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 38,
    "description": "motion picture cinema film with a bluish tint",
    "launched": 2022,
    "datasheet": "datasheets/orwo-nc400.pdf",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20NC400%22",
    "image": "orwo-nc400-135.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo NC500",
    "iso": 400,
    "format": "135",
    "color": "color",
    "type": "negative",
    "emulsion": "",
    "price": 3,
    "popularity": 38,
    "description": "motion picture cinema film with a yellowish tint",
    "launched": 2022,
    "datasheet": "datasheets/orwo-nc500.pdf",
    "lomography": "",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20NC500%22",
    "image": "orwo-nc500-135.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo NP100",
    "iso": 100,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 17,
    "description": "Orwo UN54 with an additional antihalation layer for preventing the formation of a reflection halo and improved sharpness",
    "launched": 2022,
    "datasheet": "datasheets/orwo-np100.pdf",
    "lomography": "https://www.lomography.de/films/871962412-orwo-np-100/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20NP100%22",
    "image": "orwo-np100-135.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo PF2",
    "iso": 3,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 1,
    "popularity": 90,
    "description": "fine grain orthochromatic film with a transparent film base",
    "launched": 2010,
    "datasheet": "datasheets/orwo-pf2.pdf",
    "lomography": "https://www.lomography.de/films/871947407-orwo-pf2/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20PF2%22",
    "image": "random.png"
  },
  {
    "company": "Filmotec Wolfen",
    "name": "Orwo UN54",
    "iso": 100,
    "format": "135",
    "color": "black & white",
    "type": "",
    "emulsion": "",
    "price": 2,
    "popularity": 6529,
    "description": "panchromatic motion picture cinema film",
    "launched": 2022,
    "datasheet": "datasheets/orwo-un54.pdf",
    "lomography": "https://www.lomography.de/films/871952973-orwo-un54/photos",
    "flickr": "https://www.flickr.com/search/?media=photos&text=%22Orwo%20UN54%22",
    "image": "random.png"
  }
]
